[phases.setup]
nixPkgs = ["python312"]

[phases.install]
cmds = [
    "cd backend && pip install -r requirements.txt"
]

[start]
cmd = "cd backend && gunicorn wsgi:app --bind 0.0.0.0:$PORT"

[variables]
PYTHONPATH = "/app/backend"
PYTHONUNBUFFERED = "1"
NIXPACKS_PYTHON_VERSION = "3.12"
