[phases.setup]
nixPkgs = ["python312", "gcc"]
aptPkgs = ["python3-pip", "python3-dev", "build-essential"]

[phases.install]
cmds = [
    "python3 -m pip install --upgrade pip",
    "cd backend && python3 -m pip install -r requirements.txt"
]

[start]
cmd = "cd backend && python3 -m gunicorn wsgi:app --bind 0.0.0.0:$PORT"

[variables]
PYTHONPATH = "/app/backend"
PYTHONUNBUFFERED = "1"
