[phases.setup]
nixPkgs = ["python312"]

[phases.install]
cmds = ["cd backend && python -m pip install -r requirements.txt"]

[start]
cmd = "cd backend && python -m gunicorn wsgi:app --bind 0.0.0.0:$PORT"
