[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[env]
PYTHONPATH = "/app/backend"
PYTHONUNBUFFERED = "1"
NIXPACKS_PYTHON_VERSION = "3.12.1"
