[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn main:app --bind 0.0.0.0:8080"
healthcheckPath = "/"
healthcheckTimeout = 100
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
