[build]
builder = "NIXPACKS"
buildCommand = "cd backend"

[deploy]
startCommand = "cd backend && gunicorn wsgi:app --bind 0.0.0.0:$PORT"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
