[build]
builder = "NIXPACKS"
nixpacksConfigPath = "backend/nixpacks.toml"
buildCommand = "pip install -r backend/requirements.txt"

[deploy]
startCommand = "gunicorn --chdir backend wsgi:app --bind 0.0.0.0:$PORT --log-level debug"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[env]
PYTHONPATH = "/app/backend"
PYTHONUNBUFFERED = "1"
NIXPACKS_PYTHON_VERSION = "3.12.1"
